"""
Data schema definitions (Pydantic models).
This module defines the structure of request and response objects
to ensure type validation and data consistency.
"""

from pydantic import BaseModel, Field, ConfigDict
from typing import List, Optional
from enum import Enum

class MessageRole(str, Enum):
    """Supported roles in the conversation."""
    SYSTEM = "system"
    USER = "user"
    ASSISTANT = "assistant"
    TOOL = "tool"

class ChatMessage(BaseModel):
    """
    Represents an individual message within a conversation.
    """
    model_config = ConfigDict(from_attributes=True)

    role: MessageRole
    content: str

class ChatContext(BaseModel):
    """
    Contextual information about the user's current navigation state.
    """
    url: Optional[str] = Field(None, description="Current full URL in Angular")
    project_slug: Optional[str] = Field(None, description="Identifier of the project being viewed")
    page: Optional[str] = Field(None, description="Page type (e.g., 'home', 'project_details')")

class ChatRequest(BaseModel):
    """
    Schema for the chat request sent by the client.
    """
    model_config = ConfigDict(from_attributes=True)

    query: Optional[str] = Field(None, min_length=1, max_length=500, description="User question or command")
    session_id: Optional[str] = Field(None, description="Unique ID for conversation thread and persistence")
    action: Optional[str] = Field("chat", description="Action to perform: 'init' for greeting or 'chat' for normal interaction")
    history: Optional[List[ChatMessage]] = Field(default_factory=list, description="Previous conversation history")
    context: Optional[ChatContext] = Field(None, description="Navigation context from the frontend")

class ChatResponse(BaseModel):
    """
    Schema for the response returned by the system.
    """
    model_config = ConfigDict(from_attributes=True)

    response: str = Field(..., description="Response generated by WALTER_AI's neural core")

# --- Portfolio Data Models (Validation) ---

class SystemInfo(BaseModel):
    id: str
    version: str
    status: str
    location: dict
    uptime_start: str

class TerminalInfo(BaseModel):
    welcome_message: str
    command_suggestions: List[str]
    boot_sequence: List[str]

class Profile(BaseModel):
    network: str
    username: str
    url: str

class Basics(BaseModel):
    name: str
    label: str
    system_label: str
    summary: str
    email: str
    website: str
    url: str
    profiles: List[Profile]

class SkillCategory(BaseModel):
    category: str
    items: List[str]

class WorkExperience(BaseModel):
    company: str
    role: str
    period: str
    summary: str
    image: Optional[str] = None
    highlights: List[str]

class ProjectLinks(BaseModel):
    github: Optional[str] = None
    demo: Optional[str] = None

class ProjectMetadata(BaseModel):
    status: str
    role: str
    complexity: str
    challenges: str
    solutions: str

class Project(BaseModel):
    id: str
    slug: str
    name: str
    description: str
    long_description: str
    image: str
    images: List[str]
    stack: List[str]
    period: str
    links: ProjectLinks
    metadata: ProjectMetadata

class Education(BaseModel):
    institution: str
    degree: str
    period: str

class Language(BaseModel):
    name: str
    level: str

class PortfolioData(BaseModel):
    """Root model for data.json validation."""
    system: SystemInfo
    terminal: TerminalInfo
    basics: Basics
    skills: List[SkillCategory]
    work: List[WorkExperience]
    projects: List[Project]
    education: List[Education]
    languages: List[Language]
