"""
Data schema definitions (Pydantic models).
This module defines the structure of request and response objects
to ensure type validation and data consistency.
"""

from pydantic import BaseModel, Field, ConfigDict
from typing import List, Optional
from enum import Enum

class MessageRole(str, Enum):
    """Supported roles in the conversation."""
    SYSTEM = "system"
    USER = "user"
    ASSISTANT = "assistant"
    TOOL = "tool"

class ChatMessage(BaseModel):
    """
    Represents an individual message within a conversation.
    """
    model_config = ConfigDict(from_attributes=True)

    role: MessageRole
    content: str

class ChatContext(BaseModel):
    """
    Contextual information about the user's current navigation state.
    """
    url: Optional[str] = Field(None, description="Current full URL in Angular")
    project_slug: Optional[str] = Field(None, description="Identifier of the project being viewed")
    page: Optional[str] = Field(None, description="Page type (e.g., 'home', 'project_details')")

class ChatRequest(BaseModel):
    """
    Schema for the chat request sent by the client.
    """
    model_config = ConfigDict(from_attributes=True)

    query: Optional[str] = Field(None, min_length=1, max_length=500, description="User question or command")
    session_id: Optional[str] = Field(None, description="Unique ID for conversation thread and persistence")
    action: Optional[str] = Field("chat", description="Action to perform: 'init' for greeting or 'chat' for normal interaction")
    history: Optional[List[ChatMessage]] = Field(default_factory=list, description="Previous conversation history")
    context: Optional[ChatContext] = Field(None, description="Navigation context from the frontend")

class ChatResponse(BaseModel):
    """
    Schema for the response returned by the system.
    """
    model_config = ConfigDict(from_attributes=True)

    response: str = Field(..., description="Response generated by WALTER_AI's neural core")
