"""
Data schema definitions (Pydantic models).
This module defines the structure of request and response objects
to ensure type validation and data consistency.
"""

from pydantic import BaseModel, Field, ConfigDict
from typing import List, Optional
from enum import Enum

class MessageRole(str, Enum):
    """Supported roles in the conversation."""
    SYSTEM = "system"
    USER = "user"
    ASSISTANT = "assistant"
    TOOL = "tool"

class ChatMessage(BaseModel):
    """
    Represents an individual message within a conversation.
    """
    model_config = ConfigDict(from_attributes=True)

    role: MessageRole
    content: str

class ChatContext(BaseModel):
    """
    Contextual information about the user's current navigation state.
    """
    url: Optional[str] = Field(None, description="Current full URL in Angular")
    project_slug: Optional[str] = Field(None, description="Identifier of the project being viewed")
    page: Optional[str] = Field(None, description="Page type (e.g., 'home', 'project_details')")

class ChatRequest(BaseModel):
    """
    Schema for the chat request sent by the client.
    """
    model_config = ConfigDict(from_attributes=True)

    query: Optional[str] = Field(None, min_length=1, max_length=500, description="User question or command")
    session_id: Optional[str] = Field(None, description="Unique ID for conversation thread and persistence")
    action: Optional[str] = Field("chat", description="Action to perform: 'init' for greeting or 'chat' for normal interaction")
    history: Optional[List[ChatMessage]] = Field(default_factory=list, description="Previous conversation history")
    context: Optional[ChatContext] = Field(None, description="Navigation context from the frontend")

class AgentAction(BaseModel):
    """
    Represents a structured action to be performed by the frontend.
    """
    type: str = Field(..., description="Action type (e.g., 'navigation', 'highlight')")
    target: Optional[str] = Field(None, description="Target destination (for navigation)")
    element_type: Optional[str] = Field(None, description="Type of element (for highlight)")
    item_id: Optional[str] = Field(None, description="Specific item identifier (slug)")

class ChatResponse(BaseModel):
    """
    Schema for the response returned by the system.
    """
    model_config = ConfigDict(from_attributes=True)

    message: str = Field(..., description="Response text generated by WALTER-AI")
    actions: List[AgentAction] = Field(default_factory=list, description="List of actions to trigger in the frontend")

# --- Portfolio Data Models (Validation) ---

class Profile(BaseModel):
    network: str
    username: str
    url: str

class Basics(BaseModel):
    name: str
    label: str
    summary: str
    email: str
    website: str
    url: str
    profiles: List[Profile]
    location: Optional[str] = None
    open_to_relocate: Optional[bool] = None
    open_to: Optional[str] = None

class SkillCategory(BaseModel):
    category: str
    items: List[str]

class WorkExperience(BaseModel):
    company: str
    role: str
    period: str
    summary: str
    image: Optional[str] = None
    highlights: List[str]
    achievements: Optional[List[str]] = None
    metrics: Optional[List[str]] = None

class ProjectLinks(BaseModel):
    github: Optional[str] = None
    demo: Optional[str] = None

class ProjectMetadata(BaseModel):
    status: str
    role: str
    complexity: str
    challenges: str
    solutions: str

class Project(BaseModel):
    id: str
    slug: str
    name: str
    description: str
    long_description: str
    image: str
    images: List[str]
    stack: List[str]
    period: str
    links: ProjectLinks
    metadata: ProjectMetadata
    highlights: Optional[List[str]] = None

class Education(BaseModel):
    institution: str
    degree: str
    period: str
    note: Optional[str] = None

class Language(BaseModel):
    name: str
    level: str

class PortfolioData(BaseModel):
    """Root model for data.json validation."""
    basics: Basics
    skills: List[SkillCategory]
    work: List[WorkExperience]
    projects: List[Project]
    education: List[Education]
    languages: List[Language]
